name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: install cmake
      run: sudo apt-get install cmake
    
    - name: install gtest
      run: sudo apt-get install libgtest-dev
      
    - uses: actions/checkout@v2
    
    - name: compile & run tests
      run: make gh_test

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
