name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: install cmake
      run: sudo apt-get install cmake
    
    - name: install gtest
      run: sudo apt-get install libgtest-dev
      
    - uses: actions/checkout@v2
    
    - name: compile tests
      run: mkdir bin && make compile_test
      
    - name: run tests GCC
      run: make run_test

    - name: run tests Clang
      run: make run_test CXX=clang++
